### ISSUE TITLE
Create a test for rogue files

### ISSUE THREAD

**Issue by krackerman** [blackflux/robo-config#1041]
Test files that are created can be left in a rogue state if they task creating them no longer exists.

**Comment by simlu** [comment]
More precisely this should be done here:
https://github.com/blackflux/robo-config/blob/03bab919cb9c4b250ccdf0a458c861003ebd35bd/src/load.js#L42

Shouldn't be too hard: (1) list all files (2) check all targets (3) error if un-targeted file is present

**Comment by simlu** [comment]
Also check for invalid directories

**Comment by simlu** [comment]
Will be closed with linked pr
